// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NungSue.Entities
{
    public partial class Book
    {
        public Book()
        {
            BookAuthors = new HashSet<BookAuthor>();
            BookTags = new HashSet<BookTag>();
            Favorites = new HashSet<Favorite>();
            Histories = new HashSet<History>();
            OrderDetails = new HashSet<OrderDetail>();
            ShoppingCarts = new HashSet<ShoppingCart>();
        }

        public Guid BookId { get; set; }
        public string Barcode { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string ListOfContents { get; set; }
        public string Size { get; set; }
        public int Weight { get; set; }
        public int NumberOfPage { get; set; }
        public DateTime MontOfPublication { get; set; }
        public int Price { get; set; }
        public DateTime PublishedOn { get; set; }
        public Guid CreateBy { get; set; }
        public DateTime CreateDate { get; set; }
        public Guid? UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public Guid CategoryId { get; set; }
        public Guid PublisherId { get; set; }
        public bool IsPublish { get; set; }
        public string BookImage { get; set; }

        public virtual Category Category { get; set; }
        public virtual User CreateByNavigation { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual User UpdateByNavigation { get; set; }
        public virtual PriceOffer PriceOffer { get; set; }
        public virtual ICollection<BookAuthor> BookAuthors { get; set; }
        public virtual ICollection<BookTag> BookTags { get; set; }
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}