// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NungSue.Entities
{
    public partial class BookTag
    {
        public Guid BookId { get; set; }
        public Guid TagId { get; set; }

        public virtual Book Book { get; set; }
        public virtual Tag Tag { get; set; }
    }
}