// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using NungSue.Entities;
using System;
using System.Data;
using System.Linq;

namespace NungSue.Entities
{
    public partial class BookStoreContext
    {

        [DbFunction("DateToString", "dbo")]
        public IQueryable<DateToStringResult> DateToString(DateTime? DateTime, string Format)
        {
            return FromExpression(() => DateToString(DateTime, Format));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DateToStringResult>().HasNoKey();
        }
    }
}
