// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NungSue.Entities
{
    public partial class DateToStringResult
    {
        public string DateString { get; set; }
    }
}
