// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NungSue.Entities
{
    public partial class OrderDetail
    {
        public string DetailId { get; set; }
        public int LineNumber { get; set; }
        public int Quantity { get; set; }
        public int BookPrice { get; set; }
        public Guid BookId { get; set; }
        public string OrderId { get; set; }

        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}