// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NungSue.Entities
{
    public partial class RolePermission
    {
        public Guid RoleId { get; set; }
        public string Value { get; set; }

        public virtual Role Role { get; set; }
    }
}