// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NungSue.Entities
{
    public partial class User
    {
        public User()
        {
            BookCreateByNavigations = new HashSet<Book>();
            BookUpdateByNavigations = new HashSet<Book>();
            UserRoles = new HashSet<UserRole>();
        }

        public Guid UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public DateTime? LastLogin { get; set; }
        public string ProfileImage { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<Book> BookCreateByNavigations { get; set; }
        public virtual ICollection<Book> BookUpdateByNavigations { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}